### ISSUE TITLE
V3.0.3 won’t start

### ISSUE THREAD

**Issue by MaxPuig** [johanohly/AirTrail#307]
### The bug

I just updated from >=v3.0.0 (probably the latest).
In the previous version, i couldn’t search by flight number, so i added the AeroDataBox API. Before that I also imported a .ics file from TripIt. 
I saw that an update was available, so I updated without trying the API.
Now, when i start the docker container, I get:

```
No pending migrations to apply.
Starting server...
Loaded config from .env
Listening on 0.0.0.0:3000
 5 | import { t as toTitleCase } from "./string.js";
 6 | import { d as distanceBetween } from "./distance.js";
 7 | const prepareFlightData = (data) => {
 8 |   if (!data) return [];
 9 |   return data.map((flight) => {
10 |     const departure = flight.departure ? parseLocalizeISO(flight.departure, flight.from.tz) : null;
                                                                                        ^
TypeError: null is not an object (evaluating 'flight.from.tz')
      at <anonymous> (/app/build/server/chunks/data.js:10:84)
      at map (1:11)
      at prepareFlightData (/app/build/server/chunks/data.js:9:15)
      at _page (/app/build/server/entries/pages/_page.svelte.js:48:34)
      at children (/app/build/server/chunks/internal.js:329:9)
      at children (/app/build/server/entries/pages/_layout.svelte.js:14521:13)
      at Tooltip_provider (/app/build/server/chunks/SeatInformation.js:6792:3)
      at children (/app/build/server/entries/pages/_layout.svelte.js:14499:9)
      at slot (/app/build/server/chunks/index.js:471:5)
      at QueryClientProvider (/app/build/server/entries/pages/_layout.svelte.js:89:3)
4 | import { c as parseLocalizeISO, b as parseLocal, n as nowIn } from "./parse.js";
5 | import { t as toTitleCase } from "./string.js";
6 | import { d as distanceBetween } from "./distance.js";
7 | const prepareFlightData = (data) => {
8 |   if (!data) return [];
9 |   return data.map((flight) => {
                                  ^
TypeError: null is not an object (evaluating 'flight.from.tz')
      at /app/build/server/chunks/data.js:9:31
 5 | import { t as toTitleCase } from "./string.js";
 6 | import { d as distanceBetween } from "./distance.js";
 7 | const prepareFlightData = (data) => {
 8 |   if (!data) return [];
 9 |   return data.map((flight) => {
10 |     const departure = flight.departure ? parseLocalizeISO(flight.departure, flight.from.tz) : null;
                                                                                        ^
TypeError: null is not an object (evaluating 'flight.from.tz')
      at <anonymous> (/app/build/server/chunks/data.js:10:84)
      at map (1:11)
      at prepareFlightData (/app/build/server/chunks/data.js:9:15)
      at _page (/app/build/server/entries/pages/_page.svelte.js:48:34)
      at children (/app/build/server/chunks/internal.js:329:9)
      at children (/app/build/server/entries/pages/_layout.svelte.js:14521:13)
      at Tooltip_provider (/app/build/server/chunks/SeatInformation.js:6792:3)
      at children (/app/build/server/entries/pages/_layout.svelte.js:14499:9)
      at slot (/app/build/server/chunks/index.js:471:5)
      at QueryClientProvider (/app/build/server/entries/pages/_layout.svelte.js:89:3)
4 | import { c as parseLocalizeISO, b as parseLocal, n as nowIn } from "./parse.js";
5 | import { t as toTitleCase } from "./string.js";
6 | import { d as distanceBetween } from "./distance.js";
7 | const prepareFlightData = (data) => {
8 |   if (!data) return [];
9 |   return data.map((flight) => {
                                  ^
TypeError: null is not an object (evaluating 'flight.from.tz')
      at /app/build/server/chunks/data.js:9:31
 5 | import { t as toTitleCase } from "./string.js";
 6 | import { d as distanceBetween } from "./distance.js";
 7 | const prepareFlightData = (data) => {
 8 |   if (!data) return [];
 9 |   return data.map((flight) => {
10 |     const departure = flight.departure ? parseLocalizeISO(flight.departure, flight.from.tz) : null;
                                                                                        ^
TypeError: null is not an object (evaluating 'flight.from.tz')
      at <anonymous> (/app/build/server/chunks/data.js:10:84)
      at map (1:11)
      at prepareFlightData (/app/build/server/chunks/data.js:9:15)
      at _page (/app/build/server/entries/pages/_page.svelte.js:48:34)
      at children (/app/build/server/chunks/internal.js:329:9)
      at children (/app/build/server/entries/pages/_layout.svelte.js:14521:13)
      at Tooltip_provider (/app/build/server/chunks/SeatInformation.js:6792:3)
      at children (/app/build/server/entries/pages/_layout.svelte.js:14499:9)
      at slot (/app/build/server/chunks/index.js:471:5)
      at QueryClientProvider (/app/build/server/entries/pages/_layout.svelte.js:89:3)
```

### Operating System that is running AirTrail

Docker on Raspberry Pi with Debian

### AirTrail Version

v3.0.3

### Your docker-compose.yml content

```YAML
services:
  db:
    container_name: airtrail_db
    image: postgres:16-alpine
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE_NAME}
      interval: 5s
      timeout: 5s
      retries: 5
  airtrail:
    container_name: airtrail
    image: johly/airtrail:latest
    restart: always
    env_file:
      - .env
    ports:
      - 3012:3000
    depends_on:
      db:
        condition: service_healthy
volumes:
  db_data: null
networks: {}
```

### Your .env content

```Shell

```

### Reproduction steps

1.
2.
3.
...

### Relevant log output

```shell

```

**Comment by johanohly** [comment]
Thankfully the error itself is self-explanatory, but I do want to investigate the cause of it. 
This means that one of your flights has a null `from` field (departure airport). 

Can you execute this in the `Tools` -> `SQL Console` (`/tools/sql`)?
```
SELECT * FROM flight WHERE from_id IS NULL
```
Redact any PII if you'd like of course.

**Comment by MaxPuig** [comment]
34 rows don’t have the from_id nor to_id.
I also checked `SELECT * FROM flight` with 34 rows.
So 34/34 are missing it

**Comment by johanohly** [comment]
Are they all imported from a single source? And just to make sure, `SELECT COUNT(1) FROM airport` _does_ show airports right?

**Comment by MaxPuig** [comment]
Count 83556, 1 row.
What do you mean imported from a single source? Most of them are manually added, and some were imported eith tripit .ics.
Edit: I am taking a flight now, so I won’t be able to answer immediately 😅

**Comment by johanohly** [comment]
Haha that's fine. Just to make sure, this wasn't an issue on v3.0.0 but did become an issue in a later release?

**Comment by MaxPuig** [comment]
Correct. I must have been on the latest one at the time: v3.0.2, as i wasn’t getting any warning to update.
I also manually updated the airport db from the settings. Maybe that affected it?

**Comment by johanohly** [comment]
Oh, I’m pretty sure updating the airport DB caused the issue. I hadn’t retested that function with the new v3 airport structure, which means the departure and arrival airports are lost if they weren’t exported beforehand.
I’ll get this fixed ASAP.

**Comment by MaxPuig** [comment]
The dashboard said:
Deleted: 83556
Updated: 0
New: 83556

**Comment by johanohly** [comment]
Yeah I was afraid that was the case. This means all flights referenced the old airports which were wrongfully deleted. I hope you have a backup that can help you.

**Comment by MaxPuig** [comment]
Unfortunately I don't have a backup. But it is only 34 flights and I have the flight ID, I hope it doesn't take too long :)

**Comment by johanohly** [comment]
Sorry about this - this is pretty much the worst thing that can happen in AirTrail, and it definitely shouldn’t have been possible. I’ve found the issue and I'm pushing an update ASAP so it won’t happen again to any other users.

**Comment by johanohly** [comment]
This should be resolved in v3.0.4, but I recommend downloading a json export when you're done regardless.
Thank you for reporting this issue!

**Comment by MaxPuig** [comment]
I updated but it still doesn't let me access the dashboard.
I guess the next step would be to delete everything and start new.
Is there any chance that empty parameters are accepted, so they can be added later?

**Comment by johanohly** [comment]
Is it still the same error?

**Comment by johanohly** [comment]
I think I've found the error. Try updating to v3.0.5

**Comment by MaxPuig** [comment]
Yay it works again 🥳🥳
And simply pressing the "search flight" button with the existing flightID finds the airports.
Thanks for the quick fix!

**Comment by johanohly** [comment]
Awesome, I'm happy to hear it!
